# Add configuration values here, as shown below.
# mailgun_secret_api_key:
# email: tty4032@naver.com
# mailgun_domain: sandbox8b3ef788a45346f0a2d93642cc67718d.mailgun.org

#api_key: key-882796339c7be57187c0840546156f56
#domain: sandbox8b3ef788a45346f0a2d93642cc67718d.mailgun.org
#username: postmaster@sandbox8b3ef788a45346f0a2d93642cc67718d.mailgun.org
#password: 95693da4e5b35824b554a469353525ed
#gmail_username: dahun4032@gmail.com
#gmail_password: ekgns123!

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
#
